# Specify version format
version: "{build}"

# Operating system (build VM template)
os: Visual Studio 2015

# build platform, i.e. Win32 (instead of x86), x64, Any CPU. This setting is optional.
platform: 
  #- Win32
  - x64

# specify custom environment variables
environment:
  MSVC_DEFAULT_OPTIONS: ON
  BOOST_ROOT: C:\Libraries\boost_1_59_0
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_59_0\lib32-msvc-14.0

# build configuration, i.e. Debug, Release, etc.
configuration:
  #- Debug
  - Release

# scripts that are called at very beginning, before repo cloning
init:
  - cmd: cmake --version
  - cmd: msbuild /version

# clone directory
clone_folder: C:\projects\vcpkg-dart

# scripts that run after cloning repository
install:
  #- set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
  
  - if "%platform%"=="Win32" set VCPKG_ARCH=x86-windows
  - if "%platform%"=="x64"   set VCPKG_ARCH=x64-windows
  
  # clone vcpkg
  - cd C:\projects
  - git clone https://github.com/Microsoft/vcpkg
  - cd vcpkg
  
  # copy custom ports into vcpkg ports directory
  - xcopy C:\projects\vcpkg-dart\ports C:\projects\vcpkg\ports\ /S
  
  # build vcpkg
  - powershell -exec bypass scripts\bootstrap.ps1
  
  # install pacakges
  #- vcpkg install eigen3 assimp tinyxml2 opengl
  - vcpkg install eigen3:%VCPKG_ARCH% libccd:%VCPKG_ARCH%
  - vcpkg integrate install
  #- cd C:/projects/vcpkg/packages/libccd_x86-windows/lib/
  #- dir
  #- vcpkg install fcl
  #- vcpkg integrate install
  
  # install DART
  - if "%platform%"=="Win32" set CMAKE_GENERATOR_NAME=Visual Studio 14 2015
  - if "%platform%"=="x64"   set CMAKE_GENERATOR_NAME=Visual Studio 14 2015 Win64
  - cd C:\projects
  - git clone https://github.com/dartsim/dart
  - cd dart
  - md build
  - cd build
  - cmake .. -G "%CMAKE_GENERATOR_NAME%" "-DCMAKE_TOOLCHAIN_FILE=C:\projects\vcpkg\scripts\buildsystems\vcpkg.cmake" "-DCMAKE_BUILD_TYPE=%configuration%" -DBOOST_ROOT="%BOOST_ROOT%" -DBOOST_LIBRARYDIR="%BOOST_LIBRARYDIR%" -DBoost_USE_STATIC_LIBS="ON"

# scripts to run before build
#before_build:
  
build: off
test: off

on_failure:
  - type C:\projects\vcpkg\buildtrees\fcl\config-%VCPKG_ARCH%-rel-out.log
  - type C:\projects\vcpkg\buildtrees\fcl\config-%VCPKG_ARCH%-rel-err.log
