# Specify version format
version: "{build}"

# Operating system (build VM template)
os: Visual Studio 2015

# build platform, i.e. Win32 (instead of x86), x64, Any CPU. This setting is optional.
platform: 
  - Win32
  - x64

# specify custom environment variables
#environment:

# build configuration, i.e. Debug, Release, etc.
configuration:
  - Debug
  - Release

# scripts that are called at very beginning, before repo cloning
init:
  - cmd: cmake --version
  - cmd: msbuild /version

# clone directory
clone_folder: C:\projects\vcpkg-dart

# scripts that run after cloning repository
install:
  - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
  
  # install vcpkg and DART dependency libraries
  - cd C:\projects
  - git clone https://github.com/Microsoft/vcpkg
  - cd vcpkg
  - powershell -exec bypass scripts\bootstrap.ps1
  - vcpkg install eigen3 assimp
  - vcpkg integrate install
  - cd ..
  
  # build DART
  - cd C:\projects
  - git clone https://github.com/dartsim/dart
  - cd dart
  - md build
  - cmake .. "-DCMAKE_TOOLCHAIN_FILE=C:\projects\vcpkg\scripts\buildsystems\vcpkg.cmake"
  
# scripts to run before build
#before_build:

build: off
test: off
