# Specify version format
version: "{build}"

# Operating system (build VM template)
image: Visual Studio 2017

# build platform, i.e. Win32 (instead of x86), x64, Any CPU. This setting is optional.
platform: x64

# specify custom environment variables
environment:
  CMAKE_TOOLCHAIN_FILE: -DCMAKE_TOOLCHAIN_FILE="C:\tools\vcpkg\scripts\buildsystems\vcpkg.cmake"
  matrix:
    - CMAKE_GENERATOR: -G"Visual Studio 15 2017 Win64"
      CMAKE_TOOLCHAIN: -T"v141"

# build configuration, i.e. Debug, Release, etc.
configuration:
  - Debug
  - Release

# scripts that are called at very beginning, before repo cloning
init:
  - cmd: cmake --version
  - cmd: msbuild /version

# clone directory
clone_folder: C:\projects\vcpkg-dart

# scripts that run after cloning repository
install:
  # update vcpkg
  - cd C:\tools\vcpkg
  - git pull
  - .\bootstrap-vcpkg.bat
  
  - if "%platform%"=="Win32" set VCPKG_ARCH=x86-windows
  - if "%platform%"=="x64"   set VCPKG_ARCH=x64-windows
  
  # remove outdated versions
  - vcpkg remove --outdated --recurse
  
  # copy custom ports into vcpkg ports directory
  - xcopy C:\projects\vcpkg-dart\ports C:\tools\vcpkg\ports\ /S
  
  # install pacakges
  - vcpkg install --recurse --triplet %VCPKG_ARCH% dartsim
  
  - vcpkg integrate install
  
build: off
test: off

on_failure:
  - if "%platform%"=="Win32" set VCPKG_ARCH=x86-windows
  - if "%platform%"=="x64"   set VCPKG_ARCH=x64-windows
  - type C:\projects\vcpkg\buildtrees\dart\config-%VCPKG_ARCH%-rel-out.log
  - type C:\projects\vcpkg\buildtrees\dart\config-%VCPKG_ARCH%-rel-err.log
  - type C:\projects\vcpkg\buildtrees\dart\package-%VCPKG_ARCH%-rel-out.log
  - type C:\projects\vcpkg\buildtrees\dart\package-%VCPKG_ARCH%-rel-err.log
