# Azure Pipeline settings
# Ref: https://docs.microsoft.com/en-us/azure/devops/pipelines

jobs:
- job: windows_vs2019_x64
  pool:
    vmImage: 'windows-2019'
  timeoutInMinutes: 0
  strategy:
    matrix:
      Debug64:
        CONFIGURATION: 'Debug'
      Release64:
        CONFIGURATION: 'Release'
  variables:
    VCPKG_INSTALL_ROOT: $(Build.SourcesDirectory)\vcpkg
    VCPKG_ARCH: 'x64-windows'
    BUILD_TOOLSET_VERSION: '142'
    CMAKE_GENERATOR: 'Visual Studio 16 2019'
  steps:
  - script: |
      git clone -q --depth 1 https://github.com/microsoft/vcpkg.git $(VCPKG_INSTALL_ROOT)
      xcopy .\ports .\vcpkg\ports\ /S
      $(VCPKG_INSTALL_ROOT)\bootstrap-vcpkg.bat
    displayName: 'Install vcpkg'
  - script: |
      $(VCPKG_INSTALL_ROOT)\vcpkg.exe install --recurse --triplet $(VCPKG_ARCH) dartsim
      $(VCPKG_INSTALL_ROOT)\vcpkg.exe integrate install
    displayName: 'Install dartsim'
